build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
    VERSION_TAG: $CI_REGISTRY_IMAGE:v9
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG  .
    - docker push $IMAGE_TAG
    - docker build -t $VERSION_TAG .
    - docker push $VERSION_TAG